name: Android CI Develop

on:
  push:
    branches: [ "feature/payment-widget" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build debug APK
      run: ./gradlew clean assembleDebug
      
    - uses: actions/upload-artifact@v3
      with:
        name: apk-artifact
        path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: Upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.3
      with:
        appName: Toss/Toss-Payments-SDK
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: payments
        file: ./app/build/outputs/apk/debug/app-debug.apk
        debug: true
